- name: install requirement packages for pyenv
  yum: name={{ item }} state=installed
  sudo: yes
  with_items: requirements

- name: install pyenv
  shell: >-
    if ! [ -e {{ home }}/.pyenv ] ; then
    curl -L https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer | bash &&
    echo "export PATH=\$PATH:\$HOME/.pyenv/bin:\$HOME/.pyenv/shims" >> ${HOME}/.zshenv &&
    echo "eval \"\$(pyenv init -)\"" >> ${HOME}/.zshenv &&
    fi
    executable=/bin/bash
