# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

config.vm.define :mywork do |node|
  node.vm.box = "opscode-centos6.5"
  node.vm.network "private_network", ip: "192.168.33.11"
  node.vm.network "forwarded_port", guest: 81, host: 8181

  node.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/setup.yml"
    ansible.inventory_path = "provisioning/hosts"
    ansible.limit = 'all'
  end
end
  config.ssh.forward_agent = true
end
